version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - clever

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - clever

  project:
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - clever

  burndown-chart:
    build: burndown-chart/
    container_name: burndown_chart
    ports:
      - "8004:8004"
    networks:
      - clever

  cycle-time:
    build: cycle-time/
    container_name: cycle_time
    ports:
      - "8002:8002"
    networks:
      - clever
  
  lead-time:
    build: lead-time/
    container_name: lead_time
    ports:
      - "8001:8001"
    networks:
      - clever

  adoptedwork:
    build:
      context: ./adoptedwork
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    networks:
      - clever
  
  foundwork:
    build:
      context: ./found_work
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    networks:
      - clever
    
  deliveryontime:
    build:
      context: ./dot
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    networks:
      - clever

  cruft:
    build: cruft/
    container_name: cruft
    ports:
      - "8005:8005"
    networks:
      - clever

  dev-focus:
    build: dev-focus/
    container_name: dev_focus
    ports:
      - "8003:8003"
    networks:
      - clever

  backend:
    build: ./taigaProject
    container_name: backend
    ports:
      - "8010:8010"
    networks:
      - clever

  frontend:
    build: ./react-ui
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - clever

networks:
  clever:
