version: '3.8'

services:
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - clever

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - clever

  backend:
    build: ./taigaProject
    container_name: backend
    ports:
      - "8010:8010"
    networks:
      - clever

  frontend:
    build: ./react-ui
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - clever
  
  techdebt:
    build: tech-debt/
    container_name: techdebt
    ports:
      - "8006:8006"
    networks:
      - clever

networks:
  clever:
